# Generated by Django 5.0.4 on 2024-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=None, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
