# Generated by Django 5.0.4 on 2024-04-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_coupon_alter_category_title_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Price'),
        ),
    ]
