# Generated by Django 5.0.4 on 2024-04-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
