# Generated by Django 5.0.1 on 2024-04-26 14:51

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_reviews_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to=shop.models.image_upload, verbose_name='Image'),
        ),
    ]
