# Generated by Django 5.0.4 on 2024-04-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address1',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
