# Generated by Django 5.0.4 on 2024-04-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_order_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
