# Generated by Django 5.0.4 on 2024-04-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_f_name_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.FloatField(default=50),
        ),
    ]
