# Generated by Django 5.0.4 on 2024-04-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_order_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('ratio', models.IntegerField(verbose_name='Ratio')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('expiry_date', models.DateField(null=True, verbose_name='Expires at')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.offer', verbose_name='Offer'),
        ),
    ]
