# Generated by Django 5.0.4 on 2024-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_offer_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(null=True, verbose_name='Offer Price'),
        ),
    ]
