# Generated by Django 5.0.4 on 2024-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Offer Price'),
        ),
    ]
