# Generated by Django 5.0.1 on 2024-04-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_product_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
