# Generated by Django 5.0.4 on 2024-04-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
