# Generated by Django 5.0.1 on 2024-04-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
