# Generated by Django 5.0.1 on 2024-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
